name: Test Elixir Project
description: Checks out the code and runs the test
inputs:
  elixir-version:
    required: true
    description: Elixir version to set up
  otp-version:
    required: true
    description: OTP version to set up
  ssh-key:
    description: SSH key to use for the CI
    required: true
  #################################################################
  # Everything below this line is optional.
  #################################################################
  check-test:
    description: "Run test with coverage"
    default: 'true'
    required: false
  check-test-with-coverage-and-warnings-as-errors:
    description: "Run test with coverage and warnings as errors"
    default: 'false'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Elixir Project
      uses: myriad-actions/elixir-setup@v1
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        ssh-key: ${{ inputs.ssh-key }}
      env:
        MIX_ENV: test
    
    - name: Run tests with coverage
      run: mix test --cover
      shell: sh
      if: inputs.check-test == 'true'

    - name: Run tests with coverage and warnings as errors
      run: mix test --cover --warnings-as-errors
      shell: sh
      if: ${{ inputs.check-test-with-coverage-and-warnings-as-errors == 'true' }}
  
